
from Rem.coc import *
import numpy as np


def test_PtoP():
    p1 = Rem_W_Empty()
    print(p1.full_proof())
    p2 = Rem_Ax_Prop(p1)
    print(p2.full_proof())
    p3 = Rem_IsSort(Type_i(1))
    print(p3.full_proof())
    p4 = Rem_Cont_Not_Contain_Var(Var("P"), Context())
    print(p4.full_proof())
    p5 = Rem_W_Local_Assum(p2, p3, p4)
    print(p5.full_proof())
    p6 = Rem_Cont_Contain_Typing(LocalTyping(Var("P"), Prop()), p5.Gamma)
    print(p6.full_proof())
    p7 = Rem_Var(p5, p6)
    print(p7.full_proof())
    p8 = Rem_IsSort(Prop())
    print(p8.full_proof())
    p9 = Rem_Cont_Not_Contain_Var(Var("p"), p6.Gamma)
    print(p9.full_proof())
    p10 = Rem_W_Local_Assum(p7, p8, p9)
    print(p10.full_proof())
    p11 = Rem_Cont_Contain_Typing(LocalTyping(Var("P"), Prop()), p10.Gamma)
    print(p11.full_proof())
    p12 = Rem_Var(p10, p11)
    print(p12.full_proof())
    p13 = Rem_Prod_Prop(p7, p8, p12)
    print(p13.full_proof())
    p14 = Rem_Cont_Contain_Typing(LocalTyping(Var("p"), Var("P")), p10.Gamma)
    print(p14.full_proof())
    p15 = Rem_Var(p10, p14)
    print(p15.full_proof())
    p16 = Rem_Lam(p13, p15)
    print(p16.full_proof())
    p17 = Rem_Prod_Prop(p7, p8, p12)
    print(p17.full_proof())
    p18 = Rem_Prod_Prop(p2, p3, p17)
    print(p18.full_proof())
    p19 = Rem_Env_Not_Contain_Const(Const("id"), Environment())
    print(p19.full_proof())
    p20 = Rem_W_Global_Def(p18, p19)
    print(p20.full_proof())